"""Database configuration and connection helpers for the PrivacyOps web app.

SQLite remains the zero-configuration local backend. Set DATABASE_URL to a
PostgreSQL connection string for hosted environments. Schema creation is kept
explicit and backend-aware; versioned migrations will replace this bootstrap
once the first PostgreSQL deployment is validated.
"""
from __future__ import annotations

import os
import sqlite3
from pathlib import Path
from typing import Any

BASE_DIR = Path(__file__).resolve().parent
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
IS_POSTGRES = DATABASE_URL.startswith(("postgres://", "postgresql://"))


def _sqlite_connect():
    conn = sqlite3.connect(BASE_DIR / "privacyops.db", timeout=10)
    conn.execute("PRAGMA busy_timeout = 10000")
    conn.row_factory = sqlite3.Row
    return conn


class PostgresConnection:
    """Small compatibility adapter for the app's existing DB-API call sites."""

    def __init__(self, connection: Any):
        self._connection = connection

    def execute(self, sql: str, params=()):
        statement = sql.strip()
        # PostgreSQL uses ON CONFLICT rather than SQLite's INSERT OR IGNORE.
        ignore_insert = statement.upper().startswith("INSERT OR IGNORE INTO ")
        if ignore_insert:
            statement = statement.replace("INSERT OR IGNORE INTO ", "INSERT INTO ", 1)
            statement = statement.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
        statement = statement.replace("?", "%s")
        cursor = self._connection.cursor()
        cursor.execute(statement, params)
        return cursor

    def commit(self):
        self._connection.commit()

    def close(self):
        self._connection.close()


def connect():
    """Return a SQLite or PostgreSQL connection based on DATABASE_URL."""
    if not DATABASE_URL:
        return _sqlite_connect()
    if not IS_POSTGRES:
        raise RuntimeError(
            "DATABASE_URL must be a PostgreSQL URL beginning postgres:// or postgresql://."
        )
    try:
        import psycopg
        from psycopg.rows import dict_row
    except ImportError as exc:
        raise RuntimeError(
            "PostgreSQL is configured but psycopg is not installed. Install project requirements."
        ) from exc
    connection = psycopg.connect(DATABASE_URL, row_factory=dict_row, connect_timeout=10)
    return PostgresConnection(connection)


def ensure_schema(conn) -> None:
    """Create the current schema if absent; safe to run repeatedly."""
    if IS_POSTGRES:
        statements = [
            """CREATE TABLE IF NOT EXISTS cases (
                id TEXT PRIMARY KEY, subject_email TEXT NOT NULL, request_type TEXT NOT NULL,
                jurisdiction TEXT NOT NULL, assurance_level INTEGER NOT NULL, status TEXT NOT NULL,
                deadline TEXT, results_json TEXT NOT NULL, response_json TEXT NOT NULL,
                audit_json TEXT NOT NULL, created_at TEXT NOT NULL, owner_id TEXT
            )""",
            """CREATE TABLE IF NOT EXISTS consents (
                id TEXT PRIMARY KEY, subject_email TEXT NOT NULL, purpose TEXT NOT NULL,
                data_categories TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL,
                withdrawn_at TEXT, audit_json TEXT NOT NULL DEFAULT '[]',
                propagation_json TEXT NOT NULL DEFAULT '[]', owner_id TEXT
            )""",
            """CREATE TABLE IF NOT EXISTS users (
                id TEXT PRIMARY KEY, provider TEXT NOT NULL, email TEXT, name TEXT,
                created_at TEXT NOT NULL, last_seen_at TEXT NOT NULL
            )""",
            """CREATE TABLE IF NOT EXISTS activity_events (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id TEXT NOT NULL, method TEXT NOT NULL, path TEXT NOT NULL,
                created_at TEXT NOT NULL
            )""",
        ]
        for statement in statements:
            conn.execute(statement)
        ensure_column(conn, "cases", "owner_id", "TEXT")
        ensure_column(conn, "consents", "owner_id", "TEXT")
        return

    conn.execute("""CREATE TABLE IF NOT EXISTS cases (
        id TEXT PRIMARY KEY, subject_email TEXT NOT NULL, request_type TEXT NOT NULL,
        jurisdiction TEXT NOT NULL, assurance_level INTEGER NOT NULL, status TEXT NOT NULL,
        deadline TEXT, results_json TEXT NOT NULL, response_json TEXT NOT NULL,
        audit_json TEXT NOT NULL, created_at TEXT NOT NULL, owner_id TEXT
    )""")
    conn.execute("""CREATE TABLE IF NOT EXISTS consents (
        id TEXT PRIMARY KEY, subject_email TEXT NOT NULL, purpose TEXT NOT NULL,
        data_categories TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL,
        withdrawn_at TEXT, audit_json TEXT NOT NULL DEFAULT '[]',
        propagation_json TEXT NOT NULL DEFAULT '[]', owner_id TEXT
    )""")
    conn.execute("""CREATE TABLE IF NOT EXISTS users (
        id TEXT PRIMARY KEY, provider TEXT NOT NULL, email TEXT, name TEXT,
        created_at TEXT NOT NULL, last_seen_at TEXT NOT NULL
    )""")
    conn.execute("""CREATE TABLE IF NOT EXISTS activity_events (
        id INTEGER PRIMARY KEY AUTOINCREMENT, user_id TEXT NOT NULL,
        method TEXT NOT NULL, path TEXT NOT NULL, created_at TEXT NOT NULL
    )""")
    ensure_column(conn, "cases", "owner_id", "TEXT")
    ensure_column(conn, "consents", "owner_id", "TEXT")


def ensure_column(conn, table: str, column: str, definition: str) -> None:
    if IS_POSTGRES:
        allowed = {"cases", "consents"}
        if table not in allowed:
            raise ValueError("Unexpected table name for schema update.")
        conn.execute(f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {column} {definition}")
        return
    columns = {row["name"] for row in conn.execute(f"PRAGMA table_info({table})")}
    if column not in columns:
        conn.execute(f"ALTER TABLE {table} ADD COLUMN {column} {definition}")
