"""Versioned database migrations.

Each migration is recorded only after it succeeds. Migrations run at application
startup, not every time a request opens a database connection.
"""
from datetime import datetime, timezone

from database import IS_POSTGRES, connect


def _create_core_tables(conn):
    if IS_POSTGRES:
        statements = [
            """CREATE TABLE IF NOT EXISTS cases (
                id TEXT PRIMARY KEY, subject_email TEXT NOT NULL, request_type TEXT NOT NULL,
                jurisdiction TEXT NOT NULL, assurance_level INTEGER NOT NULL, status TEXT NOT NULL,
                deadline TEXT, results_json TEXT NOT NULL, response_json TEXT NOT NULL,
                audit_json TEXT NOT NULL, created_at TEXT NOT NULL, owner_id TEXT
            )""",
            """CREATE TABLE IF NOT EXISTS consents (
                id TEXT PRIMARY KEY, subject_email TEXT NOT NULL, purpose TEXT NOT NULL,
                data_categories TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL,
                withdrawn_at TEXT, audit_json TEXT NOT NULL DEFAULT '[]',
                propagation_json TEXT NOT NULL DEFAULT '[]', owner_id TEXT
            )""",
            """CREATE TABLE IF NOT EXISTS users (
                id TEXT PRIMARY KEY, provider TEXT NOT NULL, email TEXT, name TEXT,
                created_at TEXT NOT NULL, last_seen_at TEXT NOT NULL
            )""",
            """CREATE TABLE IF NOT EXISTS activity_events (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id TEXT NOT NULL, method TEXT NOT NULL, path TEXT NOT NULL,
                created_at TEXT NOT NULL
            )""",
        ]
    else:
        statements = [
            """CREATE TABLE IF NOT EXISTS cases (
                id TEXT PRIMARY KEY, subject_email TEXT NOT NULL, request_type TEXT NOT NULL,
                jurisdiction TEXT NOT NULL, assurance_level INTEGER NOT NULL, status TEXT NOT NULL,
                deadline TEXT, results_json TEXT NOT NULL, response_json TEXT NOT NULL,
                audit_json TEXT NOT NULL, created_at TEXT NOT NULL, owner_id TEXT
            )""",
            """CREATE TABLE IF NOT EXISTS consents (
                id TEXT PRIMARY KEY, subject_email TEXT NOT NULL, purpose TEXT NOT NULL,
                data_categories TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL,
                withdrawn_at TEXT, audit_json TEXT NOT NULL DEFAULT '[]',
                propagation_json TEXT NOT NULL DEFAULT '[]', owner_id TEXT
            )""",
            """CREATE TABLE IF NOT EXISTS users (
                id TEXT PRIMARY KEY, provider TEXT NOT NULL, email TEXT, name TEXT,
                created_at TEXT NOT NULL, last_seen_at TEXT NOT NULL
            )""",
            """CREATE TABLE IF NOT EXISTS activity_events (
                id INTEGER PRIMARY KEY AUTOINCREMENT, user_id TEXT NOT NULL,
                method TEXT NOT NULL, path TEXT NOT NULL, created_at TEXT NOT NULL
            )""",
        ]
    for statement in statements:
        conn.execute(statement)


def _ensure_owner_columns(conn):
    if IS_POSTGRES:
        conn.execute("ALTER TABLE cases ADD COLUMN IF NOT EXISTS owner_id TEXT")
        conn.execute("ALTER TABLE consents ADD COLUMN IF NOT EXISTS owner_id TEXT")
        return
    for table in ("cases", "consents"):
        columns = {row["name"] for row in conn.execute(f"PRAGMA table_info({table})")}
        if "owner_id" not in columns:
            conn.execute(f"ALTER TABLE {table} ADD COLUMN owner_id TEXT")


MIGRATIONS = [
    (1, "create_core_tables", _create_core_tables),
    (2, "ensure_record_ownership_columns", _ensure_owner_columns),
]


def run_migrations():
    """Apply each pending migration once and record its version."""
    conn = connect()
    try:
        if IS_POSTGRES:
            conn.execute("""CREATE TABLE IF NOT EXISTS schema_migrations (
                version INTEGER PRIMARY KEY, name TEXT NOT NULL, applied_at TEXT NOT NULL
            )""")
        else:
            conn.execute("""CREATE TABLE IF NOT EXISTS schema_migrations (
                version INTEGER PRIMARY KEY, name TEXT NOT NULL, applied_at TEXT NOT NULL
            )""")
        conn.commit()
        rows = conn.execute("SELECT version FROM schema_migrations").fetchall()
        applied = {row["version"] if isinstance(row, dict) else row["version"] for row in rows}
        for version, name, apply in MIGRATIONS:
            if version in applied:
                continue
            apply(conn)
            conn.execute(
                "INSERT INTO schema_migrations (version, name, applied_at) VALUES (?, ?, ?)",
                (version, name, datetime.now(timezone.utc).isoformat()),
            )
            conn.commit()
    except Exception:
        conn.close()
        raise
    conn.close()
